# -*- coding: utf-8 -*-
"""ADAL4_lineal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Fb282sZEP9WRJigAf8zLx0ZXO1fNmdQ

**ALGORITMO LINEAL**
"""

f = open('file.txt', 'r')
NroRutas = int(f.readline()) 
Rutas = []
for i in range(NroRutas):
  NroCalles = int(f.readline()) 
  Calles = []

  for j in range(NroCalles-1):
    costo = int(f.readline())
    Calles.append(costo)
  Rutas.append(Calles)


RutaNumero = 1
for RutaActual in Rutas :
  mayor = 0
  secuencia = []

  CostoTemp = 0
  TempSecuencia = []

  CalleActual = 1
  TempSecuencia.append(CalleActual)
  
  for Costo in RutaActual :
    CalleActual+=1
    TempSecuencia.append(CalleActual)
    CostoTemp += Costo

    if mayor <= CostoTemp :
      mayor = CostoTemp
      secuencia = TempSecuencia[:]

    if CostoTemp <= 0 :
      CostoTemp = 0
      TempSecuencia = []
      TempSecuencia.append(CalleActual)

  if mayor != 0 : 
    print("La mejor parte de la ruta "+str(RutaNumero)+" es entre las calles "+str(secuencia[0])+" y "+str(secuencia[len(secuencia)-1]) ) 
  else:
    print("La ruta "+str(RutaNumero)+" no tiene calles interesantes")
  
  RutaNumero += 1