# -*- coding: utf-8 -*-
"""LAB6ADA_MAX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19oNJJVg3CxV9HtLVgj4NWBs72B4bisIG
"""

pip install tabulate

#Alumna: Barrios Cornejo Selene

#Librerias
import random
from math import log as ln
from tabulate import tabulate # para las tablas
import matplotlib.pyplot as plt 
from math import log2

def maximo(A):
  max = A[0]
  contador=0
  for i in range(1, len(A)):
    if A[i]>max:
      max=A[i]
      contador=contador+1
  return contador 

def Generando2(n, a=1000,b=10000):
  A = [None] * n
  for i in range(n):
    A[i] = random.randint(a, b)
  return A
#Hacemos una lista por compresion para 
#generar 200 vectores de tamaño 256, 512, 1024, ... 2^20
tam_vec = [2 ** x for x in range(8,21)]

#Para mis graficas
x=[]
y=[]
y1=[]
print(' i ', '  prom  ','  ln(i)+1  ')
for i in tam_vec:
  cont=0
  x.append(i)
  for j in range(200):
    A=Generando2(i,1000,10000)
    cont += maximo(A)
    A.clear()
    prom=cont/200
  y.append(prom)
  y1.append(ln(i)+1)
  resultados=[[i,prom,ln(i)+1]]
  print(tabulate(resultados,tablefmt='grid'))

#PLOT
plt.title('ln(i)+1 vs prom')
plt.plot(x,y,color ='b',label='prom')
plt.plot(x,y1,color ='r',label='ln(i)+1')
plt.grid(True)

plt.legend()
plt.xlabel('n')
plt.ylabel('times')